from typing import Any, Optional

RetryWhitelist: Any

class Session:
    logged_in: bool = ...
    id: Any = ...
    master: Any = ...
    key: Any = ...
    user_id: Any = ...
    authtype: Any = ...
    hostip: Any = ...
    user_data: Any = ...
    message: str = ...
    exclusive: bool = ...
    lockerror: Any = ...
    callnum: Any = ...
    session_data: Any = ...
    def __init__(self, args: Optional[Any] = ..., hostip: Optional[Any] = ...): ...
    def __getattr__(self, name: Any): ...
    def validate(self): ...
    def get_remote_ip(self, override: Optional[Any] = ...): ...
    def checkLoginAllowed(self, user_id: Any) -> None: ...
    def login(self, user: Any, password: Any, opts: Optional[Any] = ...): ...
    def getConnInfo(self): ...
    def sslLogin(self, proxyuser: Optional[Any] = ...): ...
    def makeExclusive(self, force: bool = ...) -> None: ...
    def makeShared(self) -> None: ...
    def logout(self) -> None: ...
    def logoutChild(self, session_id: Any) -> None: ...
    def createSession(self, user_id: Any, hostip: Any, authtype: Any, master: Optional[Any] = ...): ...
    def subsession(self): ...
    def getPerms(self): ...
    def hasPerm(self, name: Any): ...
    def assertPerm(self, name: Any) -> None: ...
    def assertLogin(self) -> None: ...
    def hasGroup(self, group_id: Any): ...
    def isUser(self, user_id: Any): ...
    def assertUser(self, user_id: Any) -> None: ...
    def getHostId(self): ...
    def getUserId(self, username: Any): ...
    def getUserIdFromKerberos(self, krb_principal: Any): ...
    def createUser(self, name: Any, usertype: Optional[Any] = ..., status: Optional[Any] = ..., krb_principal: Optional[Any] = ..., krb_princ_check: bool = ...): ...
    def setKrbPrincipal(self, name: Any, krb_principal: Any, krb_princ_check: bool = ...): ...
    def removeKrbPrincipal(self, name: Any, krb_principal: Any): ...
    def createUserFromKerberos(self, krb_principal: Any): ...
    def checkKrbPrincipal(self, krb_principal: Any) -> None: ...

def get_user_groups(user_id: Any): ...
def get_user_perms(user_id: Any): ...
def get_user_data(user_id: Any): ...
def login(*args: Any, **opts: Any): ...
def krbLogin(*args: Any, **opts: Any): ...
def sslLogin(*args: Any, **opts: Any): ...
def logout(): ...
def subsession(): ...
def logoutChild(session_id: Any): ...
def exclusiveSession(*args: Any, **opts: Any): ...
def sharedSession(): ...
